"""create_all_tables

Revision ID: cd4ac8289d5d
Revises: 
Create Date: 2026-06-09 14:43:12.814542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd4ac8289d5d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('nickname', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('ai_insights',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('insight_type', sa.String(length=30), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('analysis_range_start', sa.Date(), nullable=True),
    sa.Column('analysis_range_end', sa.Date(), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lifestyle_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('sleep_hours', sa.DECIMAL(precision=3, scale=1), nullable=True),
    sa.Column('sleep_quality', sa.SmallInteger(), nullable=True),
    sa.Column('stress_level', sa.SmallInteger(), nullable=True),
    sa.Column('exercise', sa.Boolean(), nullable=True),
    sa.Column('diet_tags', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'log_date', name='uq_user_log_date')
    )
    op.create_index('idx_user_date', 'lifestyle_logs', ['user_id', 'log_date'], unique=False)
    op.create_table('medications',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('default_dose', sa.String(length=50), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('outbreaks',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('severity', sa.SmallInteger(), nullable=True),
    sa.Column('location_text', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('trigger_guess', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_started', 'outbreaks', ['user_id', 'started_at'], unique=False)
    op.create_table('uas7_scores',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('score_date', sa.Date(), nullable=False),
    sa.Column('wheal_score', sa.SmallInteger(), nullable=False),
    sa.Column('itch_score', sa.SmallInteger(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'score_date', name='uq_user_score_date')
    )
    op.create_index('idx_user_date', 'uas7_scores', ['user_id', 'score_date'], unique=False)
    op.create_table('weather_snapshots',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('snapshot_at', sa.DateTime(), nullable=False),
    sa.Column('temperature', sa.DECIMAL(precision=5, scale=1), nullable=True),
    sa.Column('humidity', sa.SmallInteger(), nullable=True),
    sa.Column('pressure', sa.SmallInteger(), nullable=True),
    sa.Column('pollen_index', sa.SmallInteger(), nullable=True),
    sa.Column('aqi', sa.SmallInteger(), nullable=True),
    sa.Column('weather_desc', sa.String(length=50), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_snapshot', 'weather_snapshots', ['user_id', 'snapshot_at'], unique=False)
    op.create_table('medication_records',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('medication_id', sa.BigInteger(), nullable=False),
    sa.Column('dose', sa.String(length=50), nullable=False),
    sa.Column('taken_at', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_prn', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['medication_id'], ['medications.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_taken', 'medication_records', ['user_id', 'taken_at'], unique=False)
    op.create_table('medication_reminders',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('medication_id', sa.BigInteger(), nullable=False),
    sa.Column('reminder_time', sa.Time(), nullable=False),
    sa.Column('days_of_week', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('dose', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['medication_id'], ['medications.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('photos',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('body_part', sa.String(length=50), nullable=True),
    sa.Column('taken_at', sa.DateTime(), nullable=True),
    sa.Column('outbreak_id', sa.BigInteger(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['outbreak_id'], ['outbreaks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('outbreak_details',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('outbreak_id', sa.BigInteger(), nullable=False),
    sa.Column('body_part', sa.String(length=50), nullable=True),
    sa.Column('symptom_type', sa.String(length=50), nullable=True),
    sa.Column('severity', sa.SmallInteger(), nullable=True),
    sa.Column('photo_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['outbreak_id'], ['outbreaks.id'], ),
    sa.ForeignKeyConstraint(['photo_id'], ['photos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('outbreak_details')
    op.drop_table('photos')
    op.drop_table('medication_reminders')
    op.drop_index('idx_user_taken', table_name='medication_records')
    op.drop_table('medication_records')
    op.drop_index('idx_user_snapshot', table_name='weather_snapshots')
    op.drop_table('weather_snapshots')
    op.drop_index('idx_user_date', table_name='uas7_scores')
    op.drop_table('uas7_scores')
    op.drop_index('idx_user_started', table_name='outbreaks')
    op.drop_table('outbreaks')
    op.drop_table('medications')
    op.drop_index('idx_user_date', table_name='lifestyle_logs')
    op.drop_table('lifestyle_logs')
    op.drop_table('ai_insights')
    op.drop_table('users')
    # ### end Alembic commands ###
