"""add air quality detail fields to weather_snapshots

Revision ID: f71120d78ccc
Revises: fe03766c862e
Create Date: 2026-06-10 13:36:47.276795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f71120d78ccc'
down_revision: Union[str, Sequence[str], None] = 'fe03766c862e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weather_snapshots', sa.Column('aqi_category', sa.String(length=20), nullable=True))
    op.add_column('weather_snapshots', sa.Column('aqi_primary', sa.String(length=20), nullable=True))
    op.add_column('weather_snapshots', sa.Column('pm25', sa.DECIMAL(precision=7, scale=1), nullable=True))
    op.add_column('weather_snapshots', sa.Column('pm10', sa.DECIMAL(precision=7, scale=1), nullable=True))
    op.add_column('weather_snapshots', sa.Column('no2', sa.DECIMAL(precision=7, scale=1), nullable=True))
    op.add_column('weather_snapshots', sa.Column('so2', sa.DECIMAL(precision=7, scale=1), nullable=True))
    op.add_column('weather_snapshots', sa.Column('co', sa.DECIMAL(precision=7, scale=2), nullable=True))
    op.add_column('weather_snapshots', sa.Column('o3', sa.DECIMAL(precision=7, scale=1), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('weather_snapshots', 'o3')
    op.drop_column('weather_snapshots', 'co')
    op.drop_column('weather_snapshots', 'so2')
    op.drop_column('weather_snapshots', 'no2')
    op.drop_column('weather_snapshots', 'pm10')
    op.drop_column('weather_snapshots', 'pm25')
    op.drop_column('weather_snapshots', 'aqi_primary')
    op.drop_column('weather_snapshots', 'aqi_category')
    # ### end Alembic commands ###
